/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Leonardo Faêda
 */
public class JFprincipal extends javax.swing.JFrame {
    int tipoacesso=0;
    /**
     * Creates new form JFprincipal
     */
    public JFprincipal() {
        initComponents();
        setExtendedState(JFprincipal.MAXIMIZED_BOTH);

    }
    
    public JFprincipal(int tipoacesso) {
        initComponents();
        setExtendedState(JFprincipal.MAXIMIZED_BOTH);
        this.tipoacesso=tipoacesso;
        hideAndShow();
    }
    
    public void hideAndShow(){
        if(tipoacesso==2){
          itemmenu1.setVisible(false);
            itemmenu3.setVisible(false);
            //btn1.setVisible(false);
            btn3.setVisible(false);
            btn4.setVisible(false);
            btnPreco.setVisible(false);
        }else if(tipoacesso==1){
            itemmenu3.setVisible(false);
            btn3.setVisible(false);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn5 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnPreco = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        itemmenu1 = new javax.swing.JMenuItem();
        itemmenu2 = new javax.swing.JMenuItem();
        itemmenu3 = new javax.swing.JMenuItem();
        itemmenu4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        btn5.setText("Sair");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        btn1.setText("Compras/Vendas");
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relat.png"))); // NOI18N
        btn2.setText("Relatórios");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_person_add_black_24dp_2x.png"))); // NOI18N
        btn3.setText("Novo Usuário");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_build_black_24dp_2x.png"))); // NOI18N
        btn4.setText("Status Máquina");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_attach_money_black_24dp_2x.png"))); // NOI18N
        btnPreco.setText("Preço da Ficha");
        btnPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecoActionPerformed(evt);
            }
        });

        menu1.setText("Controle");

        itemmenu1.setText("Funcionário");
        itemmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenu1ActionPerformed(evt);
            }
        });
        menu1.add(itemmenu1);

        itemmenu2.setText("Cliente");
        itemmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenu2ActionPerformed(evt);
            }
        });
        menu1.add(itemmenu2);

        itemmenu3.setText("Gerente");
        itemmenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenu3ActionPerformed(evt);
            }
        });
        menu1.add(itemmenu3);

        itemmenu4.setText("Máquinas");
        itemmenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenu4ActionPerformed(evt);
            }
        });
        menu1.add(itemmenu4);

        jMenuItem1.setText("Fichas");
        menu1.add(jMenuItem1);

        jMenuBar1.add(menu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(btnPreco)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenu1ActionPerformed
        JFprincipalFuncionario funcionario = new JFprincipalFuncionario();
        funcionario.setVisible(true);
    }//GEN-LAST:event_itemmenu1ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        JFescolhaTrocas trocas = new JFescolhaTrocas();
        trocas.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void itemmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenu2ActionPerformed
        JFprincipalCliente cliente = new JFprincipalCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_itemmenu2ActionPerformed

    private void itemmenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenu3ActionPerformed
        JFprincipalGerente gerente = new JFprincipalGerente();
        gerente.setVisible(true);
    }//GEN-LAST:event_itemmenu3ActionPerformed

    private void itemmenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenu4ActionPerformed
        JFprincipalMaquinas maquina = new JFprincipalMaquinas();
        maquina.setVisible(true);
    }//GEN-LAST:event_itemmenu4ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        JFescolhaRelatorio relatorio = new JFescolhaRelatorio();
        relatorio.setVisible(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        JFprincipalLogin login = new JFprincipalLogin();
        login.setVisible(true);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        JFstatusMaquina status = new JFstatusMaquina();
        status.setVisible(true);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecoActionPerformed
        JFficha ficha = new JFficha();
        ficha.setVisible(true);
    }//GEN-LAST:event_btnPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btnPreco;
    private javax.swing.JMenuItem itemmenu1;
    private javax.swing.JMenuItem itemmenu2;
    private javax.swing.JMenuItem itemmenu3;
    private javax.swing.JMenuItem itemmenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menu1;
    // End of variables declaration//GEN-END:variables
}
